[package]
name = "net"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3"
dns-lookup = "2.0"
local-ip-address = "0.6"
log = "0.4"
openssl = { version = "0.10", features = ["vendored"] }
serde = { version = "^1", features = ["derive"] }
simplelog = "^0.12.0"
thiserror = "2"